### ISSUE TITLE
I'd like implement your DSP to GDSII

### ISSUE THREAD

**Issue by cyrushuang19** [ahmedshahein/DSP-RTL-Lib#1]
Hi, 
I am testing advanced N7 process node on high performance core, is it possible to implement your DSP to GDSII ?

**Comment by ahmedshahein** [comment]
Hi,
I have tested it using YoSys and Vivado, so I guess it ready to back-end flow.
Regards

**Comment by ahmedshahein** [comment]
Since I didn't heard back from you I assume it has been resolved.
